name: Generate Profile

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 5"

jobs:
  generate_profile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm install
      - run: npm run generate
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          YOUTUBE_CHANNEL_ID: ${{ secrets.YOUTUBE_CHANNEL_ID }}
      - run: |
          git config user.name "manucastrillonm"
          git config user.email "manu.cm43@gmail.com"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "[bot] Update README"
          git push origin main
